<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'confoo\\mess\\api' => '/API.php',
                'confoo\\mess\\exception' => '/Exception.php',
                'confoo\\mess\\inmemoryuserrepository' => '/InMemoryUserRepository.php',
                'confoo\\mess\\invalidemailexception' => '/InvalidEmailException.php',
                'confoo\\mess\\invalidmessageexception' => '/InvalidMessageException.php',
                'confoo\\mess\\invalidtokenexception' => '/InvalidTokenException.php',
                'confoo\\mess\\invalidusernameexception' => '/InvalidUsernameException.php',
                'confoo\\mess\\message' => '/Message.php',
                'confoo\\mess\\notauthorizedexception' => '/NotAuthorizedException.php',
                'confoo\\mess\\service' => '/Service.php',
                'confoo\\mess\\token' => '/Token.php',
                'confoo\\mess\\user' => '/User.php',
                'confoo\\mess\\usernameunavailableexception' => '/UsernameUnavailableException.php',
                'confoo\\mess\\userrepository' => '/UserRepository.php',
                'confoo\\mess\\userrepositoryexception' => '/UserRepositoryException.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd